name: axis_assignment
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following package adds localization system.
  flutter_localizations:
    sdk: flutter

  # The following package adds Cupertino Icons font.
  cupertino_icons: ^1.0.8

  intl: ^0.19.0


  # The following package for the network and API calls.
  http: ^1.2.1
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.3
  dartz: ^0.10.1

  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  infinite_scroll_pagination: ^4.0.0

  # The following package for simple offline cache storage.
  shared_preferences: ^2.2.3

  loading_animation_widget: ^1.2.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.2
  photo_view: ^0.15.0
  path_provider: ^2.1.3

  fluttertoast: ^8.2.6
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0

  # Local storage.
  objectbox: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.10
  objectbox_generator: ^4.0.1
  objectbox_flutter_libs: ^4.0.1

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application.
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/

