name: axis_assignment
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following package adds localization system.
  flutter_localizations:
    sdk: flutter

  # The following package adds Cupertino Icons font.
  cupertino_icons: ^1.0.6

  intl: ^0.18.1


  # The following package for the network and API calls.
  http: ^0.13.5
  internet_connection_checker: ^1.0.0+1
  dartz: ^0.10.1

  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  infinite_scroll_pagination: ^3.2.0

  # The following package for simple offline cache storage.
  shared_preferences: ^2.0.15

  loading_animation_widget: ^1.2.0+4
  flutter_svg: ^2.0.5
  cached_network_image: ^3.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application.
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/

